//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Last.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunSet
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string kod { get; set; }
        public string aciklama { get; set; }
        public int miktar { get; set; }
        public string resim { get; set; }
    }
}
